### ISSUE TITLE
Add hover effect

### ISSUE THREAD

**Issue by kubamahnert** [Hahihula/github_extension#2]
Amazing work! Thank you.

Is it possible to add a hover effect for the button for better usability?

Also, continuing on https://github.com/Hahihula/github_extension/issues/1, maybe the visual style could be unified with other GitHub buttons. This would solve both issues.

**Comment by Hahihula** [comment]
Thanks for the suggestion!
I've changed the orange border to the standard GitHub button as you've suggested.
It really seems much more appropriate. The change is in the repository and was published to the store as version 0.0.2.
